version: '3.8'
services:
  # client:
  #   container_name: client
  #   build: ./client
  #   ports:
  #     - '5173:5173'
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  server:
    container_name: server 
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ~/Projects/pgdata:/var/lib/postgresql/data